#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="analytics.service"

python3 -m venv env
. env/bin/activate
pip install --require-hashes -r requirements.txt

mkdir -p ~/.config/systemd/user

read -p "Enter the port for the service [2000]: " PORT
PORT=${PORT:-2000}

sed "s/PORT/$PORT/g" "$SERVICE_NAME" > ~/.config/systemd/user/"$SERVICE_NAME"
systemctl --user daemon-reload
systemctl --user enable --now "$SERVICE_NAME"

echo "Installed and started $SERVICE_NAME"
