"""Remove referrer from Pageview model

Revision ID: af3ee8730146
Revises: f0fa1c1b309a
Create Date: 2025-11-30 06:14:40.542770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3ee8730146'
down_revision: Union[str, Sequence[str], None] = 'f0fa1c1b309a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pageviews', 'referrer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pageviews', sa.Column('referrer', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
