"""Add session_id to Pageview model

Revision ID: c720765f1194
Revises: 32c41fff6d7d
Create Date: 2025-11-02 11:11:44.914162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import secrets


# revision identifiers, used by Alembic.
revision: str = 'c720765f1194'
down_revision: Union[str, Sequence[str], None] = '32c41fff6d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('pageviews', sa.Column('session_id', sa.String(), nullable=False, server_default=secrets.token_urlsafe(16)))
    with op.batch_alter_table('pageviews') as batch_op:
        batch_op.alter_column('session_id', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pageviews', 'session_id')
    # ### end Alembic commands ###
