"""Remove is_bot from Pageview model

Revision ID: f0fa1c1b309a
Revises: 4d3528a58609
Create Date: 2025-11-17 04:24:16.548827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fa1c1b309a'
down_revision: Union[str, Sequence[str], None] = '4d3528a58609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pageviews', 'is_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pageviews', sa.Column('is_bot', sa.BOOLEAN(), nullable=False, server_default="false"))
    with op.batch_alter_table('pageviews') as batch_op:
        batch_op.alter_column('is_bot', server_default=None)
    # ### end Alembic commands ###
